/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyDOS;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import easyDOS.Auxiliares;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author josel
 */
public class InfoJuego extends javax.swing.JFrame {

    Boolean play = false;
    Juego _juego = new Juego();
    Auxiliares aux = new Auxiliares();

    /**
     * Creates new form test
     */
    public InfoJuego() {
        initComponents();
        btnDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnPlay.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnCancel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.pack();
        this.setLocationRelativeTo(null);
        UrlImg.setVisible(false);
    }

    public InfoJuego(Juego g, Boolean flag) {
        initComponents();
        btnDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnPlay.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnCancel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        BufferedImage img = aux.loadImage(g.getImagen());
        ImageIcon icon = new ImageIcon(img);
        Caratula.setIcon(icon);
        TextCompany.setText(g.getCompania());
        TextDesarrollador.setText(g.getDesarrollador());
        TextNombre.setText(g.getNombre());
        TextDescripcion.append(g.getDescrip());
        TextGenero.setText(g.getTipo());
        UrlImg.setText(g.getImagen());
        this.pack();
        this.setLocationRelativeTo(null);
        if (flag) {
            btnPlay.setText("Jugar");
            btnPlay.setActionCommand("Play");
            play = true;
            _juego = g;
            btnDelete.setVisible(true);
            btnDelete.setVisible(true);
            TextDescripcion.setEditable(false);
            TextDescripcion.setEnabled(false);
        } else {
            btnPlay.setText("Añadir a Mis Juegos");
            btnPlay.setActionCommand("Add");
            play = false;
            btnDelete.setVisible(false);
            btnDelete.setVisible(false);
            TextDescripcion.setEditable(false);
            TextDescripcion.setEnabled(false);
        }
        if (g.getImagen().equals("/img/AddGameUnknown.png") && TextNombre.getText().equals("")) {
            btnPlay.setVisible(false);
            TextCompany.setEditable(true);
            TextGenero.setEditable(true);
            TextDesarrollador.setEditable(true);
            TextDescripcion.setEditable(true);
            TextNombre.setEditable(true);
            btnPlay.setText("Añadir nuevo Juego");
            btnPlay.setActionCommand("AddNuevo");
            btnPlay.setVisible(true);
            btnDelete.setVisible(false);
            TextDescripcion.setEditable(true);
            TextDescripcion.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UrlImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Caratula = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        LCompany = new javax.swing.JLabel();
        LDesarrollador = new javax.swing.JLabel();
        LDescripcion = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        TextCompany = new javax.swing.JTextField();
        TextDesarrollador = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextDescripcion = new javax.swing.JTextArea();
        btnPlay = new keeptoo.KButton();
        btnCancel = new keeptoo.KButton();
        btnDelete = new javax.swing.JLabel();
        LDesarrollador1 = new javax.swing.JLabel();
        TextGenero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setOpaque(false);

        Caratula.setPreferredSize(new java.awt.Dimension(150, 171));

        LNombre.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LNombre.setForeground(new java.awt.Color(255, 255, 255));
        LNombre.setText("Nombre: ");

        LCompany.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LCompany.setForeground(new java.awt.Color(255, 255, 255));
        LCompany.setText("Compañia:");

        LDesarrollador.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LDesarrollador.setForeground(new java.awt.Color(255, 255, 255));
        LDesarrollador.setText("Desarrollador:");

        LDescripcion.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        LDescripcion.setText("Descripción");

        TextNombre.setEditable(false);
        TextNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextCompany.setEditable(false);
        TextCompany.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        TextDesarrollador.setEditable(false);
        TextDesarrollador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        TextDescripcion.setColumns(20);
        TextDescripcion.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        TextDescripcion.setLineWrap(true);
        TextDescripcion.setRows(5);
        TextDescripcion.setWrapStyleWord(true);
        TextDescripcion.setOpaque(false);
        jScrollPane2.setViewportView(TextDescripcion);

        btnPlay.setText("Jugar");
        btnPlay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPlay.setkEndColor(new java.awt.Color(153, 0, 153));
        btnPlay.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        btnPlay.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnPlay.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        btnPlay.setkSelectedColor(new java.awt.Color(102, 102, 255));
        btnPlay.setkStartColor(new java.awt.Color(102, 204, 255));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlayMouseClicked(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancel.setkEndColor(new java.awt.Color(153, 0, 153));
        btnCancel.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        btnCancel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnCancel.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        btnCancel.setkSelectedColor(new java.awt.Color(102, 102, 255));
        btnCancel.setkStartColor(new java.awt.Color(102, 204, 255));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-32.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setToolTipText("Eliminar este juego");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteMousePressed(evt);
            }
        });

        LDesarrollador1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LDesarrollador1.setForeground(new java.awt.Color(255, 255, 255));
        LDesarrollador1.setText("Género:");

        TextGenero.setEditable(false);
        TextGenero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LCompany)
                                    .addComponent(LNombre)
                                    .addComponent(LDesarrollador1)
                                    .addComponent(LDesarrollador))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextCompany)
                                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(TextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TextDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Caratula, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LDescripcion)
                        .addGap(608, 608, 608))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNombre)
                            .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LCompany)
                            .addComponent(TextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LDesarrollador1))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LDesarrollador)
                            .addComponent(TextDesarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Caratula, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(LDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 777, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
            // TODO add your handling code here:
	}//GEN-LAST:event_kButton1ActionPerformed

	private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
            // TODO add your handling code here:
	}//GEN-LAST:event_kButton2ActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
            // TODO add your handling code here:
            this.dispose();
	}//GEN-LAST:event_btnCancelActionPerformed

	private void btnPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseClicked
            // TODO add your handling code here:
            String action = btnPlay.getText();
            switch (action) {
                case "Añadir nuevo Juego":
                    AddJuego();
                    break;
                case "Close":
                    this.dispose();
                case "Jugar":
                    break;
                case "Añadir a Mis Juegos":
                    AddJuego();
                    break;
            }
	}//GEN-LAST:event_btnPlayMouseClicked
    void AddJuego() {
        AddJuego frameJuego = new AddJuego();
        frameJuego.setVisible(true);
        frameJuego.setTitle("Añadir juego " + TextNombre.getText());
        frameJuego.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        frameJuego.addWindowListener(new WindowListener() {
            @Override
            public void windowClosed(WindowEvent e) {
                //Si se ha cerrado la ventana se comprueba el title
                if (!frameJuego.getTitle().equals("Error")) {
                    //El juego se va a insertar
                    String url = null;
                    try {
                        String ruta = frameJuego.getTitle();
                        url = new java.io.File(".").getCanonicalPath();
                        url = url.replace("\\", "/");
                        url = url + "/Juegos/default.txt";
                        final String _url = url;
                        btnPlay.setText("Finalizar Configuración");
                        btnPlay.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                try (Writer output = new BufferedWriter(new FileWriter(_url, true))) {
                                    String Nombre = TextNombre.getText();
                                    String Desarrollador = TextDesarrollador.getText();
                                    String Compania = TextCompany.getText();
                                    String Genero = TextGenero.getText();
                                    String Descripcion = TextDescripcion.getText();
                                    String imagen = UrlImg.getText();
                                    UrlImg.setEnabled(false);
                                    if (Nombre.equals("") || Nombre.isEmpty() || Nombre.equals(" ")
                                            || Desarrollador.equals("") || Desarrollador.isEmpty() || Desarrollador.equals(" ")
                                            || Compania.equals("") || Compania.isEmpty() || Compania.equals(" ")
                                            || Descripcion.equals("") || Descripcion.isEmpty() || Descripcion.equals(" ")
                                            || Genero.equals("") || Genero.isEmpty() || Genero.equals(" ")) {
                                        //eL NOMBRE NO ESTA DEFINIDO
                                        TextNombre.setBackground(Color.red);
                                        TextNombre.setForeground(Color.white);
                                        TextDesarrollador.setBackground(Color.red);
                                        TextDesarrollador.setForeground(Color.white);
                                        TextCompany.setBackground(Color.red);
                                        TextCompany.setForeground(Color.white);
                                        TextDescripcion.setBackground(Color.red);
                                        TextDescripcion.setForeground(Color.white);
                                        TextGenero.setBackground(Color.red);
                                        TextGenero.setForeground(Color.white);
                                    } else {
                                        Juego j = new Juego(100, Nombre, Desarrollador, Compania, Genero, Descripcion, imagen);
                                        output.append(Nombre + "," + ruta + "\n");
                                        output.close();
                                        rehacerBiblioteca(j);
                                        finalizar();
                                    }
                                } catch (IOException ex) {
                                    Logger.getLogger(InfoJuego.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        });
                    } catch (IOException ex) {
                        Logger.getLogger(InfoJuego.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }

            //Funciones de ventana no usadas para nuestro problema
            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });

    }

    private void rehacerBiblioteca(Juego j) throws FileNotFoundException, IOException {
        String file = new java.io.File(".").getCanonicalPath();
        file = file.replace("\\", "/");
        file = file + "/Juegos/listado_juegos.txt";

        FileReader f = new FileReader(file);
        BufferedReader b = new BufferedReader(f);
        String cadena;
        //FICHERO AUXILIAR
        String url = new java.io.File(".").getCanonicalPath();
        url = url.replace("\\", "/");
        url = url + "/Juegos/temp.txt";

        File file2 = new File(url);
        file2.createNewFile();

        FileWriter fw = new FileWriter(file2);

        while ((cadena = b.readLine()) != null) {
            fw.append(cadena + "\n");
        }
        if (j.getImagen().equals("/img/AddGameUnknown.png")) {
            fw.append(j.getNombre() + "\n");
            fw.append(j.getCompania() + "\n");
            fw.append(j.getDesarrollador() + "\n");
            fw.append(j.getTipo() + "\n");
            fw.append(j.getDescrip() + "\n");
            fw.append(j.getImagen());
        }

        b.close();
        fw.close();

        File antiguo = new File(file);
        antiguo.delete();

        File nuevo = new File(url);
        boolean success = nuevo.renameTo(antiguo);
    }

	private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
            // TODO add your handling code here:
            if (play) {
                try {
                    String url = new java.io.File(".").getCanonicalPath();
                    url = url + "/dosBOX/DOSBoxPortable.exe";
                    url = url + " " + _juego.getUrl();
                    url = url.replace("/", "\\");
                    JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Puedes jugar en pantalla completa con Alt+Enter");
                    if (dialogResult == JOptionPane.YES_OPTION) {
                        Runtime.getRuntime().exec(url);
                        dispose();
                    }
                } catch (IOException ioe) {
                    System.out.println(ioe);
                }
            }
	}//GEN-LAST:event_btnPlayActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

        String nombreJuego = TextNombre.getText();
        try {
            borrarJuego(nombreJuego);
        } catch (IOException ex) {
            Logger.getLogger(InfoJuego.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMousePressed

    private void borrarJuego(String nombreJuego) throws FileNotFoundException, IOException {
        //FICHERO INICIAL
        String file = new java.io.File(".").getCanonicalPath();
        file = file.replace("\\", "/");
        file = file + "/Juegos/default.txt";
        FileReader f = new FileReader(file);
        BufferedReader b = new BufferedReader(f);
        String cadena;

        //FICHERO AUXILIAR
        String url = new java.io.File(".").getCanonicalPath();
        url = url.replace("\\", "/");
        url = url + "/Juegos/tempt.txt";
        File file2 = new File(url);
        file2.createNewFile();

        FileWriter fw = new FileWriter(file2);

        String[] parts;

        while ((cadena = b.readLine()) != null) {
            parts = cadena.split(",");
            if (!parts[0].replaceAll("[^\\dA-Za-z() ]", "").equals(nombreJuego)) {
                fw.append(cadena + "\n");
            }
        }
        b.close();
        fw.close();
        File antiguo = new File(file);
        antiguo.delete();
        File nuevo = new File(url);
        boolean success = nuevo.renameTo(antiguo);
    }

    private void finalizar() {
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caratula;
    private javax.swing.JLabel LCompany;
    private javax.swing.JLabel LDesarrollador;
    private javax.swing.JLabel LDesarrollador1;
    private javax.swing.JLabel LDescripcion;
    private javax.swing.JLabel LNombre;
    private javax.swing.JTextField TextCompany;
    private javax.swing.JTextField TextDesarrollador;
    private javax.swing.JTextArea TextDescripcion;
    private javax.swing.JTextField TextGenero;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JLabel UrlImg;
    private keeptoo.KButton btnCancel;
    private javax.swing.JLabel btnDelete;
    private keeptoo.KButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
